// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeNrcw2Tnuls7UugfgGeiqHOzEtanxFBA',
    appId: '1:949824855702:android:231d6bb99e3ef288456cb7',
    messagingSenderId: '949824855702',
    projectId: 'oapp-50c16',
    storageBucket: 'oapp-50c16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEyxP1sSYSrYReXtXhshf7lvOIwMT1f2I',
    appId: '1:949824855702:ios:f6b6c48ef7df6523456cb7',
    messagingSenderId: '949824855702',
    projectId: 'oapp-50c16',
    storageBucket: 'oapp-50c16.appspot.com',
    androidClientId: '949824855702-7pmn6vgfv2tp8c61cdi2g80pr7blahst.apps.googleusercontent.com',
    iosClientId: '949824855702-9r4f9v5sefja1th73ds2gbk5cn5e84pt.apps.googleusercontent.com',
    iosBundleId: 'cz.ocompany.oapp',
  );
}
